# Generated by Django 4.0.6 on 2022-07-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=20)),
                ('ProductImage', models.ImageField(upload_to='')),
                ('DateTime', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
    ]
