# Generated by Django 4.0.6 on 2022-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='PassWord',
            new_name='Password',
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(upload_to='productImage'),
        ),
    ]
